### ISSUE TITLE
Forward Application Exceptions for Triage (Email, Logging Service, Slack, Ect) 

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#28]
When a meetup group no longer exists the update_cal_data.py will catch an exception and log it.  I actually have this being emailed to me via the cronjob, but we should really consider if we should have these sorts of exceptions emailed, sent to a logging platform that sends notices, posted to a Slack channel, or otherwise shared with the people who can review and fix them.

Below is an example of when the Web Code Chicks group stopped using Meetup.com and we found out about it right away via the exception being emailed to me, but it could very well have gone unnoticed in a log.

We also have a tool that visits the event services and homepages of the organizations (need to push this code to GitHub), so this use case below is not the most necessary, but it demonstrates that we should do something with exceptions and errors. 

```
Traceback (most recent call last):

File "update_cal_data.py", line 25, in <module>
  refresh_all_meetings()
File "update_cal_data.py", line 10, in refresh_all_meetings
  meetup_events = app.get_meetup_events(group_lists['Meetup.com'])
File "/home/eventapi/upstate_tech_cal_service/app.py", line 52, in get_meetup_events
  raise Exception('Could not connect to Meetup API at {}.  Status Code: {}'.format(url, r.status_code))
Exception: Could not connect to Meetup API at https://api.meetup.com/webcodechicks/events?&sign=true&photo-host=public&page=20. Status Code: 410
```

**Comment by allella** [comment]
Another someone common thing is for Meetup, changing the group.urlname in their REST API.

The group.urlname is case sensitive, so if a Meetup group changes it's name, then their group.urlname may change.  Also, some group.urlnames that have been working for years, like 'Greer-Programmers-Group', will all of a sudden change to 'greer-programmers-group' in Meetups REST API.

The workaround do debug it is to [log the group name right before the error happens]([greer-programmers-group](https://github.com/hackgvl/events-api/issues/68#issue-1308924201)).

We're probably going to [rewrite this Events API in the Laravel stack](https://github.com/hackgvl/hackgreenville-com/issues/172), since we need to [move to Meetup's GraphQL API](https://github.com/hackgvl/events-api/issues/69) if we want to avoid the seeming inevitable depreciation of Meetup's REST API (not announced, but it seems like they are bound to eventually kill it off).

```Traceback (most recent call last):
  File "update_cal_data.py", line 24, in <module>
    refresh_all_meetings()
  File "update_cal_data.py", line 13, in refresh_all_meetings
    func.format_meetup_events(meetup_events, group_lists['Meetup.com'])
  File "/home/eventapi/upstate_tech_cal_service/update_functions.py", line 65, in format_meetup_events
    group_item = [i for i in group_list if i.get('field_events_api_key') == str(event['group']['urlname'])][0]
IndexError: list index out of range```

**Comment by ThorntonMatthewD** [comment]
Is there any preference where exceptions should be sent for review?

The project I'm currently assigned to uses Sentry and custom Slack alerts to fill this need. It looks like Sentry has a program for non-profits if that route is desired: https://sentry.io/for/good/

Email should be doable also, but my questions would move over to how to create and manage a mailing list for those alerts.

**Comment by ThorntonMatthewD** [comment]
Would there be any interest in automatically opening GitHib issues for exceptions? There would be some traceability value there, but I'm not sure what the exception volumes are like across the hg-labs apps and how many issues could end up being created.

How to handle recurring issues would also need to be addressed (add subsequent failures of the same type in the same place as a comment to an already-active thread?).

**Comment by allella** [comment]
This [issue may also depend on if we stay with Python](https://github.com/hackgvl/events-api/pull/84#issuecomment-1742361605).

Though, assuming the GitHub issue question is a new idea and I guess that depends too. 

Not to be a wet blanket on everything with "security" as the justification, but we have attracted the occasional sketchy folks so dumping error logs to public repos could expose unexpected server or config details.

The Slack may be a slightly less public alternative, but even that has some random folks slip in.

**Comment by allella** [comment]
One middle-ground is we could have a private repo, or repo(s) with only trusted folks being able to see error reports.

Though, we might do something similar by giving the same folks access to a logging service, or emailing them, or some such.

**Comment by oliviasculley** [comment]
I'd like to +1 Sentry. With it's Github integration, you can easily turn exceptions into Github issues or link them to existing issues, and then we could only have more trusted members in the Sentry organization. It's also self-hostable, so we could theoretically host it ourselves so waiting for 503c status with RefactorGVL doesn't need to hold us up.
