### ISSUE TITLE
Occasional Failure of update_cal_data.py - Possibly SSL Timeout

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#29]
@MarkMcDaniels 

Here's the error we're getting 2 or 3 times a day when the connect to Meetup.com and Eventbrite are made.  The cronjob runs every hour at :40 after the hour, so it's working more often than not without this failure.

I suspect it's a connection timeout, either SSL related, or just a timeout due to slower than normal responses from the remote APIs we're pinging.

At a minimum, it would be interesting to narrow down which connection / conditions are triggering this issue.

We could potentially add some more logging or exception handling or something to try and figure out the code that's failing.  Or, maybe the line of code is evident from studying the error and then we just need to figure out which request(s) fail and/or what timeout values are impacted and if we can/should raise those values higher.

```
Traceback (most recent call last):

File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
  chunked=chunked)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
  self._validate_conn(conn)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
  conn.connect()
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
  ssl_context=context)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
  return context.wrap_socket(sock, server_hostname=server_hostname)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/ssl.py", line 407, in wrap_socket
  _context=self, _session=session)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/ssl.py", line 817, in __init__
  self.do_handshake()
File "/home/username/miniconda/envs/cal_service/lib/python3.6/ssl.py", line 1077, in do_handshake
  self._sslobj.do_handshake()
File "/home/username/miniconda/envs/cal_service/lib/python3.6/ssl.py", line 689, in do_handshake
  self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
  timeout=timeout
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
  _stacktrace=sys.exc_info()[2])
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
  raise six.reraise(type(error), error, _stacktrace)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
  raise value.with_traceback(tb)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
  chunked=chunked)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
  self._validate_conn(conn)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
  conn.connect()
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
  ssl_context=context)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
  return context.wrap_socket(sock, server_hostname=server_hostname)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/ssl.py", line 407, in wrap_socket
  _context=self, _session=session)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/ssl.py", line 817, in __init__
  self.do_handshake()
File "/home/username/miniconda/envs/cal_service/lib/python3.6/ssl.py", line 1077, in do_handshake
  self._sslobj.do_handshake()
File "/home/username/miniconda/envs/cal_service/lib/python3.6/ssl.py", line 689, in do_handshake
  self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "update_cal_data.py", line 25, in <module>
  refresh_all_meetings()
File "update_cal_data.py", line 9, in refresh_all_meetings
  group_lists = app.get_group_lists()
File "/home/username/upstate_tech_cal_service/app.py", line 29, in get_group_lists
  r = requests.get(url)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/requests/api.py", line 72, in get
  return request('get', url, params=params, **kwargs)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/requests/api.py", line 58, in request
  return session.request(method=method, url=url, **kwargs)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
  resp = self.send(prep, **send_kwargs)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
  r = adapter.send(request, **kwargs)
File "/home/username/miniconda/envs/cal_service/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
  raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))
```

**Comment by allella** [comment]
The requests Python library says the default connection timeout is None, so not sure that's the issue here.

This is related to the call to the [orgs API](https://data.openupstate.org/rest/organizations?org_status=active&_format=json).

The logs on the orgs API show the requests are never making it to the Apache access log, as evident by the missing hourly requests shown where there are blank lines.

I'm going to look at the logs earlier in the LAMP stack.  The errors above show SSL handshake errors, so this points more strongly to an intermittent issue during the SSL negotiation between the app.py and the Orgs API.



```
162.243.48.70 - - [07-Nov-2019 20:40:23 -0500] 16464 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [07-Nov-2019 21:40:02 -0500] 21141 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"

162.243.48.70 - - [07-Nov-2019 23:40:02 -0500] 15156 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"

162.243.48.70 - - [08-Nov-2019 01:40:02 -0500] 13770 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [08-Nov-2019 02:43:54 -0500] 10666 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [08-Nov-2019 03:40:02 -0500] 16623 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [08-Nov-2019 04:43:41 -0500] 11086 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [08-Nov-2019 05:40:02 -0500] 16999 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [08-Nov-2019 06:41:15 -0500] 12489 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [08-Nov-2019 07:40:02 -0500] 28588 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [08-Nov-2019 08:40:03 -0500] 19752 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"

162.243.48.70 - - [08-Nov-2019 10:40:03 -0500] 17079 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [08-Nov-2019 11:45:22 -0500] 14329 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [08-Nov-2019 12:40:03 -0500] 28624 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [08-Nov-2019 13:44:36 -0500] 11706 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [08-Nov-2019 14:40:02 -0500] 16681 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"
162.243.48.70 - - [08-Nov-2019 15:41:24 -0500] 13043 "GET /rest/organizations?org_status=active&_format=json HTTP/1.1" 200 31648 "-" "python-requests/2.18.4"

```

**Comment by allella** [comment]
Updated the _requests_ package to the latest version 2.22.0 in the environments.yml to ensure the issue here isn't a bug as others reported related looking issues in an earlier _issue_ on the requests issue queue.

**Comment by allella** [comment]
Upgrading the requests package seemed to fix this as the error has stopped.
